# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: nexus-reg-cred
      containers:
        - name: demo-app
          image: 172.18.196.94:7000/demo-app:1   # starting tag, will be updated automatically
          ports:
            - containerPort: 3000
