apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-nexus-secret
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["nexus-reg-cred"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-image-updater-to-read-nexus-secret
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argocd
roleRef:
  kind: Role
  name: read-nexus-secret
  apiGroup: rbac.authorization.k8s.io
