apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  annotations:
    # Track the image in the private registry
    argocd-image-updater.argoproj.io/image-list: demo=172.18.196.94:7000/demo-app

    # tells Image Updater which image name inside your kustomization.yaml to update.
    argocd-image-updater.argoproj.io/demo.kustomize.image-name: 172.18.196.94:7000/demo-app

    # Only allow numeric tags (1,2,3,4...)
    argocd-image-updater.argoproj.io/demo.allow-tags: regexp:^\d+$

    # Strategy: use alphabetical (highest number wins for numeric tags)
    argocd-image-updater.argoproj.io/demo.update-strategy: latest

    # Use pull secret from argocd namespace
    argocd-image-updater.argoproj.io/demo.pull-secret: pullsecret:argocd/nexus-reg-cred

    # Write updates back directly into ArgoCD
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Koustav21-dev/demo-app.git
    targetRevision: master
    path: k8s # where deployment.yaml + service.yaml + kustomization.yaml live
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
